### ISSUE TITLE
spamspam mailing

### ISSUE THREAD

**Issue by ervitis** [ikigaikintore/ikigaikintore#327]
In this case, I had a problem with a bank entity where someone used my email to register a bank account and sometimes the user who created it is trying to log-in in his/her account or make a bank operation and the bank system is sending me its keys. So I want to automatize it to respond it with the sent key until they fix the problem.

I will use Gmail API for this

```[tasklist]
### Tasks
- [ ] https://github.com/ikigaikintore/ikigaikintore/issues/331
- [ ] https://github.com/ikigaikintore/ikigaikintore/issues/330
- [ ] https://github.com/ikigaikintore/ikigaikintore/issues/329
- [ ] https://github.com/ikigaikintore/ikigaikintore/issues/328
```
